# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70305837583721e57b00b5be07b9fc5379e7b3cb2d1dca3b6503d09dab41030d23b490a3a7f03f3a2e6026b9537a966240febefb0d7fd95e598c2bfea51647f6

test:
  secret_key_base: 3ce0544e4f1b4b7968643829370d7193837e9304ef586163cc6d5d7f775af4ac67485bf3a78745914a6b336ca6343b3bc7dea835c9ef52f24b7668fd962cfc2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
